# sudo docker-compose build
# sudo docker-compose up

version: "2"
services:
  apache_php:
    build:
      dockerfile: Dockerfile
      context: .
    image: ubuntu18_apache_php72:18.04
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:5.7.10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: visual_vert
    volumes:
      - visual_vert:/var/lib/mysql
    networks:
      - default
volumes:
  visual_vert:
